[features]
seeds = false
skip-lint = false

[programs.devnet]
nft_metadata = "BPnzXRAP6GejnumGTZp1fJzUWX5veRCgN7cJ3QAPssLv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/djaciel/.config/solana/id.json"

[scripts]
test-init = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/nft-metadata.ts"
test-nft = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-nft.ts"
